"""add outreach thread tracking

Revision ID: 1ece4aa15705
Revises: 6ad2f3a7e207
Create Date: 2026-09-15 20:49:34.784102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ece4aa15705'
down_revision: Union[str, Sequence[str], None] = '6ad2f3a7e207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outreach', sa.Column('thread_id', sa.String(length=255), nullable=True))
    op.add_column('outreach', sa.Column('last_reply_checked_message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outreach', 'last_reply_checked_message_id')
    op.drop_column('outreach', 'thread_id')
    # ### end Alembic commands ###
