"""initial schema

Revision ID: 6ad2f3a7e207
Revises: 
Create Date: 2026-09-15 02:11:16.600468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad2f3a7e207'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('location_filter', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('size_estimate', sa.String(length=64), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('austin_presence', sa.Boolean(), nullable=False),
    sa.Column('texas_presence', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('normalized_identity', sa.String(length=512), nullable=False),
    sa.Column('profile_url', sa.String(length=1024), nullable=True),
    sa.Column('current_title', sa.String(length=255), nullable=False),
    sa.Column('current_company_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('ut_status', sa.String(length=32), nullable=False),
    sa.Column('ut_status_rationale', sa.Text(), nullable=True),
    sa.Column('ut_degree', sa.String(length=255), nullable=False),
    sa.Column('ut_grad_year', sa.Integer(), nullable=True),
    sa.Column('other_education', sa.String(length=512), nullable=False),
    sa.Column('networking_thesis', sa.Text(), nullable=True),
    sa.Column('personalization_angles', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('ut_score', sa.Integer(), nullable=False),
    sa.Column('career_relevance_score', sa.Integer(), nullable=False),
    sa.Column('company_quality_score', sa.Integer(), nullable=False),
    sa.Column('seniority_score', sa.Integer(), nullable=False),
    sa.Column('geography_score', sa.Integer(), nullable=False),
    sa.Column('career_interest_score', sa.Integer(), nullable=False),
    sa.Column('relationship_value_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_identity', name='uq_people_normalized_identity')
    )
    op.create_index(op.f('ix_people_normalized_identity'), 'people', ['normalized_identity'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('fact_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_email_address'), 'emails', ['email_address'], unique=False)
    op.create_table('employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name_raw', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('fact_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(length=32), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('date_discovered', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_first_contacted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('reply_status', sa.String(length=32), nullable=True),
    sa.Column('meeting_status', sa.String(length=32), nullable=True),
    sa.Column('last_meeting', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relationship_strength', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('claim', sa.String(length=512), nullable=True),
    sa.Column('fact_type', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('subject_options', sa.JSON(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template_tag', sa.String(length=64), nullable=True),
    sa.Column('personalization_angle', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_idempotency_key'), 'outreach', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_idempotency_key'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_table('sources')
    op.drop_table('relationships')
    op.drop_table('meetings')
    op.drop_table('employment')
    op.drop_index(op.f('ix_emails_email_address'), table_name='emails')
    op.drop_table('emails')
    op.drop_table('education')
    op.drop_table('activities')
    op.drop_index(op.f('ix_people_normalized_identity'), table_name='people')
    op.drop_table('people')
    op.drop_table('settings')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
